name: todo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ">=2.15.0-172.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  lint:
  get_storage:
  get:
  flutter_local_notifications:
  flutter_native_timezone:
  intl:
  google_fonts:
  date_picker_timeline:
  sqflite:
  flutter_staggered_animations:
  flutter_svg:
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "images/appicon.jpeg"
flutter:
  uses-material-design: true
    # To add assets to your application, add an assets section, like this:
  assets:
    - images/person.jpeg
    - images/task.svg
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
